services:
  registry_mirror_docker.io:
    image: registry:2
    restart: always
    container_name: registry_mirror_docker.io
    ports:
      - "5000:5000"
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    volumes:
      - /home/registry_cache/docker.io:/var/lib/registry:rw

  local_registry:
    image: registry:2
    restart: always
    container_name: local_registry
    ports:
      - "5001:5000"
    volumes:
      - /home/registry_cache/local:/var/lib/registry:rw
