#!/bin/bash

dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-1 "['<Super>ampersand']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-2 "['<Super>eacute']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-3 "['<Super>quotedbl']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-4 "['<Super>apostrophe']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-5 "['<Super>parenleft']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-6 "['<Super>minus']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-7 "['<Super>egrave']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-8 "['<Super>underscore']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-9 "['<Super>ccedilla']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-10 "['<Super>agrave']"

dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-1 "['<Alt><Super>ampersand']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-2 "['<Alt><Super>eacute']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-3 "['<Alt><Super>quotedbl']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-4 "['<Alt><Super>apostrophe']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-5 "['<Alt><Super>parenleft']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-6 "['<Alt><Super>minus']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-7 "['<Alt><Super>egrave']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-8 "['<Alt><Super>underscore']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-9 "['<Alt><Super>ccedilla']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-10 "['<Alt><Super>agrave']"

gsettings set "org.gnome.shell.keybindings" "switch-to-application-1" "[]"
gsettings set "org.gnome.shell.keybindings" "switch-to-application-2" "[]"
gsettings set "org.gnome.shell.keybindings" "switch-to-application-3" "[]"
gsettings set "org.gnome.shell.keybindings" "switch-to-application-4" "[]"
gsettings set "org.gnome.shell.keybindings" "switch-to-application-5" "[]"
gsettings set "org.gnome.shell.keybindings" "switch-to-application-6" "[]"
gsettings set "org.gnome.shell.keybindings" "switch-to-application-7" "[]"
gsettings set "org.gnome.shell.keybindings" "switch-to-application-8" "[]"
gsettings set "org.gnome.shell.keybindings" "switch-to-application-9" "[]"

# dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-1 "[]"
# dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-2 "[]"
# dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-3 "[]"
# dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-4 "[]"
# dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-5 "[]"
# dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-6 "[]"
# dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-7 "[]"
# dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-8 "[]"
# dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-9 "[]"
# dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-10 "[]"
